apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mongo-db-pvc
   labels:
     app: mongo-db
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted as read-write by a single pod
  resources:
    requests:
      storage: 2Gi # Request 2 Gigabytes of persistent storage
