apiVersion: v1
kind: Service
metadata:
  name: mongo-db-headless-service
  labels:
    app.kubernetes.io/name: mongo
    app.kubernetes.io/instance: mongo-db
    app.kubernetes.io/part-of: mongo-loader-app
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: mongo-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017