apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-api-deployment
  labels:
    app: mongo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-api
  template:
    metadata:
      labels:
        app: mongo-api
    spec:
      containers:
        - name: fastapi-container
          image: "docker.io/a0533057932/fastapi-mongo-crud:latest"
          imagePullPolicy: Always
          command: [ "/bin/sh", "-c" ]
          args: [ "echo '--- Environment Variables ---' && printenv && echo '--- Sleeping forever ---' && sleep infinity" ]
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: "mongo-db-service"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-credentials
                  key: MONGO_DB_NAME
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-db-credentials
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-db-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD