apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-api-deployment
  labels:
    app: mongo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo-api
  template:
    metadata:
      labels:
        app: mongo-api
    spec:
      containers:
        - name: fastapi-container
          image: "docker.io/YOUR_DOCKERHUB_USERNAME/fastapi-mongo-crud:latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://$(MONGO_INITDB_ROOT_USERNAME):$(MONGO_INITDB_ROOT_PASSWORD)@mongo-db-service:27017" # <--- שינוי
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-credentials
                  key: MONGO_DB_NAME
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-credentials
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-db-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD